# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Yakup Bilen\PycharmProjects\database\widgets\uies\categories.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sql_queries
from connection import cursor

class Ui_CategoryDialog(QtWidgets.QDialog):
    def __init__(self):
        super(Ui_CategoryDialog, self).__init__()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self)


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 800)
        Dialog.setMinimumSize(QtCore.QSize(400, 600))
        Dialog.setMaximumSize(QtCore.QSize(600, 1000))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tableCategories = QtWidgets.QTableWidget(Dialog)
        self.tableCategories.setObjectName("tableCategories")
        self.tableCategories.setColumnCount(2)
        self.tableCategories.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableCategories.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.tableCategories.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.tableCategories)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 8)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def setValues(self,id=None):
        if id is None:
            self.tableCategories.setRowCount(0)
            cursor.execute(sql_queries.select_categories)
            result = cursor.fetchall()
            i = 0
            for row in result:
                self.tableCategories.insertRow(i)
                self.tableCategories.setItem(i, 0, QtWidgets.QTableWidgetItem(str(row[0])))
                self.tableCategories.setItem(i, 1, QtWidgets.QTableWidgetItem(row[1]))
                i = i + 1
            return True
        else:
            self.tableCategories.setRowCount(0)
            cursor.execute(sql_queries.select_sub_categories2,(id,))
            result = cursor.fetchall()
            if result:
                i = 0
                for row in result:
                    self.tableCategories.insertRow(i)
                    self.tableCategories.setItem(i, 0, QtWidgets.QTableWidgetItem(str(row[0])))
                    self.tableCategories.setItem(i, 1, QtWidgets.QTableWidgetItem(row[1]))
                    i = i + 1
                return True
            else:
                return False





    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableCategories.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Id"))
        item = self.tableCategories.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Name"))
