# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Yakup Bilen\PycharmProjects\pythonProject1\widgets\uies\saler_mode.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIntValidator
from PyQt5.QtWidgets import QMessageBox
from objects.select_data import Select
from connection import cursor,connection
import sql_queries
import datetime

class Ui_MakeSale(QtWidgets.QDialog):
    def __init__(self, id):
        self.id = id
        super(Ui_MakeSale, self).__init__()
        self.ui = Ui_MakeSaleDialog()
        self.ui.setupUi(self, self.id)

class Ui_MakeSaleDialog(object):
    def setupUi(self, MakeSaleDialog, id):
        MakeSaleDialog.setObjectName("MakeSaleDialog")
        MakeSaleDialog.resize(901, 800)
        MakeSaleDialog.setMinimumSize(QtCore.QSize(800, 800))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(MakeSaleDialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblId = QtWidgets.QLabel(MakeSaleDialog)
        self.lblId.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lblId.setFont(font)
        self.lblId.setObjectName("lblId")
        self.horizontalLayout_3.addWidget(self.lblId)
        self.lblName = QtWidgets.QLabel(MakeSaleDialog)
        self.lblName.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lblName.setFont(font)
        self.lblName.setObjectName("lblName")
        self.horizontalLayout_3.addWidget(self.lblName)
        self.lblRole = QtWidgets.QLabel(MakeSaleDialog)
        self.lblRole.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lblRole.setFont(font)
        self.lblRole.setObjectName("lblRole")
        self.horizontalLayout_3.addWidget(self.lblRole)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label = QtWidgets.QLabel(MakeSaleDialog)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableInvoice = QtWidgets.QTableWidget(MakeSaleDialog)
        self.tableInvoice.setObjectName("tableInvoice")
        self.tableInvoice.setColumnCount(5)
        self.tableInvoice.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableInvoice.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableInvoice.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableInvoice.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableInvoice.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableInvoice.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.tableInvoice)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_5 = QtWidgets.QLabel(MakeSaleDialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.lineTotal = QtWidgets.QLineEdit(MakeSaleDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineTotal.setFont(font)
        self.lineTotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineTotal.setReadOnly(True)
        self.lineTotal.setObjectName("lineTotal")
        self.horizontalLayout.addWidget(self.lineTotal)
        self.horizontalLayout.setStretch(0, 75)
        self.horizontalLayout.setStretch(2, 25)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(MakeSaleDialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineProductId = QtWidgets.QLineEdit(MakeSaleDialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineProductId.setFont(font)
        self.lineProductId.setObjectName("lineProductId")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineProductId)
        self.label_3 = QtWidgets.QLabel(MakeSaleDialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineAmount = QtWidgets.QLineEdit(MakeSaleDialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineAmount.setFont(font)
        self.lineAmount.setObjectName("lineAmount")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineAmount)
        self.btnAdd = QtWidgets.QPushButton(MakeSaleDialog)
        self.btnAdd.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnAdd.setFont(font)
        self.btnAdd.setObjectName("btnAdd")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btnAdd)
        self.btnCancel = QtWidgets.QPushButton(MakeSaleDialog)
        self.btnCancel.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnCancel.setFont(font)
        self.btnCancel.setObjectName("btnCancel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.btnCancel)
        self.horizontalLayout_2.addLayout(self.formLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.btnFinish = QtWidgets.QPushButton(MakeSaleDialog)
        self.btnFinish.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnFinish.setFont(font)
        self.btnFinish.setObjectName("btnFinish")
        self.verticalLayout_3.addWidget(self.btnFinish)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_2.setStretch(0, 15)
        self.horizontalLayout_2.setStretch(1, 40)
        self.horizontalLayout_2.setStretch(2, 15)
        self.horizontalLayout_2.setStretch(3, 25)
        self.horizontalLayout_2.setStretch(4, 5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.lblInfo = QtWidgets.QLabel(MakeSaleDialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lblInfo.setFont(font)
        self.lblInfo.setText("")
        self.lblInfo.setObjectName("lblInfo")
        self.horizontalLayout_4.addWidget(self.lblInfo)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.verticalLayout_2.setStretch(0, 8)
        self.verticalLayout_2.setStretch(1, 2)
        self.verticalLayout_2.setStretch(2, 2)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 1)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)

        self.tableInvoice.verticalHeader().setDefaultSectionSize(100)

        self.id = id
        self.employee = Select.select_employee(id)

        # LineEdit Validators
        self.lineProductId.setValidator(QIntValidator())
        self.lineAmount.setValidator(QIntValidator())

        # Buttons
        self.btnAdd.clicked.connect(self.addProduct)
        self.btnFinish.clicked.connect(self.finish)
        self.btnCancel.clicked.connect(self.cancel)

        # Row count
        self.row = 0
        self.invoiceList = {}
        self.products = {}

        self.retranslateUi(MakeSaleDialog)
        QtCore.QMetaObject.connectSlotsByName(MakeSaleDialog)

        self.lblId.setText(f"Id : {self.id} /")
        self.lblRole.setText(f"Role : {self.employee.job}")
        self.lblName.setText(f"Name : {self.employee.first_name} {self.employee.last_name} /")

    def cancel(self):
        self.tableInvoice.setRowCount(0)
        self.row = 0
        self.lineTotal.setText("0.00")
        self.lblInfo.setText("")
        self.invoiceList.clear()
        self.products.clear()
        self.lineProductId.clear()
        self.lineAmount.clear()

    def finish(self):
        if self.lineTotal.text() != "0.00":
            self.tableInvoice.setRowCount(0)
            self.row = 0
            finalProducts = {}
            for index in self.invoiceList:
                finalProducts[self.products[index][0] - self.invoiceList[index]] = index
            finalProducts = list(finalProducts.items())

            # Update Product Stocks
            cursor.executemany(sql_queries.update_stock_product, finalProducts)
            connection.commit()

            date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            total_price = float(self.lineTotal.text())

            # Insert Sales into Sales Table
            cursor.execute(sql_queries.insert_sales, (self.id, date, total_price))
            connection.commit()

            cursor.execute(sql_queries.select_max_sales)
            sales_id = int(cursor.fetchone()[0])

            sales_details = []
            for sale in self.invoiceList:
                temp = [sales_id, sale, self.invoiceList[sale], (self.products[sale][1] * self.invoiceList[sale])]
                sales_details.append((*temp,))

            # Insert Sales_Details into Sales_Details Table
            cursor.executemany(sql_queries.insert_sales_detail, sales_details)
            connection.commit()

            self.lblInfo.setStyleSheet("color:green;")
            self.lblInfo.setText("Sale Successfully made.")

            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText(f"Total price is : {total_price}")
            msg.setStandardButtons(QMessageBox.Ok)
            msg.exec_()

        self.lineTotal.setText("0.00")
        self.invoiceList.clear()
        self.lineAmount.clear()
        self.lineProductId.clear()

    def addProduct(self):
        self.lblInfo.setText("")
        id = self.lineProductId.text()
        amount = self.lineAmount.text()
        total_price = float(self.lineTotal.text())
        if (id != "") & (amount != ""):
            id = int(id)
            amount = int(amount)
            product = Select.select_product(id)
            if product:
                if amount > 0:
                    if id in self.invoiceList:
                        self.invoiceList[id] += amount
                    else:
                        self.invoiceList[id] = amount
                    if product.stock >= self.invoiceList[id]:
                        image = Select.getImage(product.image)
                        self.tableInvoice.insertRow(self.row)
                        self.tableInvoice.setItem(self.row, 0, QtWidgets.QTableWidgetItem(str(id)))
                        self.tableInvoice.setCellWidget(self.row, 1, image)
                        self.tableInvoice.setItem(self.row, 2, QtWidgets.QTableWidgetItem(product.name))
                        self.tableInvoice.setItem(self.row, 3, QtWidgets.QTableWidgetItem(str(amount)))
                        self.tableInvoice.setItem(self.row, 4,
                                                  QtWidgets.QTableWidgetItem(str(round(amount * product.price, 2))))
                        total_price = total_price + (amount * product.price)
                        self.lineTotal.setText(str(round(total_price, 2)))
                        self.row += 1
                        self.products[id] = [product.stock, product.price]
                    else:
                        self.lblInfo.setStyleSheet("color:red;")
                        self.lblInfo.setText("Product stock not enough!!!")
                else:
                    self.lblInfo.setStyleSheet("color:red;")
                    self.lblInfo.setText("Amount must be at least 1!!")
            else:
                self.lblInfo.setStyleSheet("color:red;")
                self.lblInfo.setText("Product doesn't exist!!")
            self.lineProductId.clear()
            self.lineAmount.clear()



    def retranslateUi(self, MakeSaleDialog):
        _translate = QtCore.QCoreApplication.translate
        MakeSaleDialog.setWindowTitle(_translate("MakeSaleDialog", "Dialog"))
        self.lblId.setText(_translate("MakeSaleDialog", "Id:"))
        self.lblName.setText(_translate("MakeSaleDialog", "Name:"))
        self.lblRole.setText(_translate("MakeSaleDialog", "Role:"))
        self.label.setText(_translate("MakeSaleDialog", "<html><head/><body><p align=\"center\">Invoice</p></body></html>"))
        item = self.tableInvoice.horizontalHeaderItem(0)
        item.setText(_translate("MakeSaleDialog", "Product Id"))
        item = self.tableInvoice.horizontalHeaderItem(1)
        item.setText(_translate("MakeSaleDialog", "Photo"))
        item = self.tableInvoice.horizontalHeaderItem(2)
        item.setText(_translate("MakeSaleDialog", "Name"))
        item = self.tableInvoice.horizontalHeaderItem(3)
        item.setText(_translate("MakeSaleDialog", "Amount"))
        item = self.tableInvoice.horizontalHeaderItem(4)
        item.setText(_translate("MakeSaleDialog", "Price"))
        self.label_5.setText(_translate("MakeSaleDialog", "Total :"))
        self.lineTotal.setText(_translate("MakeSaleDialog", "0.00"))
        self.label_2.setText(_translate("MakeSaleDialog", "Product Id :"))
        self.label_3.setText(_translate("MakeSaleDialog", "Amount :"))
        self.btnAdd.setText(_translate("MakeSaleDialog", "Add"))
        self.btnCancel.setText(_translate("MakeSaleDialog", "Cancel"))
        self.btnFinish.setText(_translate("MakeSaleDialog", "Finish"))
