# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Yakup Bilen\PycharmProjects\pythonProject1\widgets\uies\returned_sales.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIntValidator
from PyQt5.QtWidgets import QMessageBox
from objects.select_data import Select
from connection import cursor,connection
import sql_queries
import datetime


class Ui_ReturnedSales(QtWidgets.QDialog):
    def __init__(self,id):
        self.id = id
        super(Ui_ReturnedSales, self).__init__()
        self.ui = Ui_ReturnedSalesDialog()
        self.ui.setupUi(self,self.id)


class Ui_ReturnedSalesDialog(object):
    def setupUi(self, ReturnedSalesDialog, id):
        ReturnedSalesDialog.setObjectName("ReturnedSalesDialog")
        ReturnedSalesDialog.resize(1101, 800)
        ReturnedSalesDialog.setMinimumSize(QtCore.QSize(1000, 800))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(ReturnedSalesDialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblId = QtWidgets.QLabel(ReturnedSalesDialog)
        self.lblId.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lblId.setFont(font)
        self.lblId.setObjectName("lblId")
        self.horizontalLayout_3.addWidget(self.lblId)
        self.lblName = QtWidgets.QLabel(ReturnedSalesDialog)
        self.lblName.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lblName.setFont(font)
        self.lblName.setObjectName("lblName")
        self.horizontalLayout_3.addWidget(self.lblName)
        self.lblRole = QtWidgets.QLabel(ReturnedSalesDialog)
        self.lblRole.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lblRole.setFont(font)
        self.lblRole.setObjectName("lblRole")
        self.horizontalLayout_3.addWidget(self.lblRole)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label = QtWidgets.QLabel(ReturnedSalesDialog)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableInvoice = QtWidgets.QTableWidget(ReturnedSalesDialog)
        self.tableInvoice.setObjectName("tableInvoice")
        self.tableInvoice.setColumnCount(5)
        self.tableInvoice.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableInvoice.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableInvoice.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableInvoice.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableInvoice.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableInvoice.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.tableInvoice)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(ReturnedSalesDialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.lineInvoiceId = QtWidgets.QLineEdit(ReturnedSalesDialog)
        self.lineInvoiceId.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineInvoiceId.setFont(font)
        self.lineInvoiceId.setObjectName("lineInvoiceId")
        self.horizontalLayout.addWidget(self.lineInvoiceId)
        self.btnShowInvoice = QtWidgets.QPushButton(ReturnedSalesDialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnShowInvoice.setFont(font)
        self.btnShowInvoice.setObjectName("btnShowInvoice")
        self.horizontalLayout.addWidget(self.btnShowInvoice)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_5 = QtWidgets.QLabel(ReturnedSalesDialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.lineReturnedTotal = QtWidgets.QLineEdit(ReturnedSalesDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineReturnedTotal.setFont(font)
        self.lineReturnedTotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineReturnedTotal.setReadOnly(True)
        self.lineReturnedTotal.setObjectName("lineReturnedTotal")
        self.horizontalLayout.addWidget(self.lineReturnedTotal)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 2)
        self.horizontalLayout.setStretch(4, 1)
        self.horizontalLayout.setStretch(5, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(ReturnedSalesDialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineProductId = QtWidgets.QLineEdit(ReturnedSalesDialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineProductId.setFont(font)
        self.lineProductId.setObjectName("lineProductId")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineProductId)
        self.label_3 = QtWidgets.QLabel(ReturnedSalesDialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineAmount = QtWidgets.QLineEdit(ReturnedSalesDialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineAmount.setFont(font)
        self.lineAmount.setObjectName("lineAmount")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineAmount)
        self.btnReturn = QtWidgets.QPushButton(ReturnedSalesDialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnReturn.setFont(font)
        self.btnReturn.setObjectName("btnReturn")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btnReturn)
        self.horizontalLayout_2.addLayout(self.formLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.lblInfo = QtWidgets.QLabel(ReturnedSalesDialog)
        self.lblInfo.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lblInfo.setFont(font)
        self.lblInfo.setText("")
        self.lblInfo.setObjectName("lblInfo")
        self.horizontalLayout_4.addWidget(self.lblInfo)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.verticalLayout_2.setStretch(0, 8)
        self.verticalLayout_2.setStretch(1, 2)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 1)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)

        self.label_5.setText("Total Price : ")

        self.id = id
        self.employee = Select.select_employee(id)
        self.tableInvoice.verticalHeader().setDefaultSectionSize(100)
        # LineEdit Validators
        self.lineProductId.setValidator(QIntValidator())
        self.lineAmount.setValidator(QIntValidator())
        self.lineInvoiceId.setValidator(QIntValidator())

        # Buttons
        self.btnShowInvoice.clicked.connect(self.showInvoice)
        self.btnReturn.clicked.connect(self.returnProduct)

        # Row count
        self.row = 0

        self.retranslateUi(ReturnedSalesDialog)
        QtCore.QMetaObject.connectSlotsByName(ReturnedSalesDialog)

        self.lblId.setText(f"Id : {self.id} /")
        self.lblRole.setText(f"Role : {self.employee.job}")
        self.lblName.setText(f"Name : {self.employee.first_name} {self.employee.last_name} /")

    def showInvoice(self):
        id = self.lineInvoiceId.text()
        if id:
            self.tableInvoice.setRowCount(0)
            self.row = 0
            id = int(id)
            sales_details = Select.select_sales_detail(id)
            if sales_details:
                for detail in sales_details:
                    product = Select.select_product(detail.product_id)
                    image = Select.getImage(product.image)
                    self.tableInvoice.insertRow(self.row)
                    self.tableInvoice.setItem(self.row, 0, QtWidgets.QTableWidgetItem(str(detail.product_id)))
                    self.tableInvoice.setCellWidget(self.row, 1, image)
                    self.tableInvoice.setItem(self.row, 2, QtWidgets.QTableWidgetItem(product.name))
                    self.tableInvoice.setItem(self.row, 3, QtWidgets.QTableWidgetItem(str(detail.amount)))
                    self.tableInvoice.setItem(self.row, 4, QtWidgets.QTableWidgetItem(str(detail.price)))
                    self.row += 1
                cursor.execute("SELECT total_price FROM Sales WHERE id=?",(id,))
                total_price = cursor.fetchone()[0]
                self.lineReturnedTotal.setText(str(round(total_price,2)))

    def returnProduct(self):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)
        msg.setStandardButtons(QMessageBox.Ok)
        invoiceId = self.lineInvoiceId.text()
        productId = self.lineProductId.text()
        amount = self.lineAmount.text()
        if (invoiceId != "") & (productId != "") & (amount != "") & (int(amount) > 0):
            amount = int(amount)
            cursor.execute(sql_queries.select_sales, (invoiceId,))
            invoice_detail = cursor.fetchone()
            total_price = invoice_detail[3]
            invoice = Select.select_sales_detail(invoiceId)
            product = Select.select_product(productId)
            if invoice:
                if product:
                    for detail in invoice:
                        if detail.product_id == product.id:
                            # if the quantity of the purchased product is more than the refunded
                            if detail.amount > amount:
                                returned_price = amount * product.price

                                # Update product stock
                                cursor.execute(sql_queries.update_stock_product, (product.stock + amount, product.id))
                                connection.commit()

                                # Update invoice detail
                                cursor.execute(sql_queries.update_sales_detail,
                                               (detail.amount - amount, detail.price - returned_price,
                                                detail.sales_id, product.id))
                                connection.commit()

                                # Update invoice
                                cursor.execute(sql_queries.update_sales, (total_price - returned_price, invoiceId))
                                connection.commit()
                                self.lineReturnedTotal.setText(str(round(total_price - returned_price,2)))
                                msg.setText(f"Returned Price is {returned_price}")
                                msg.exec_()
                            # if the quantity of the purchased item is the same as the returned item
                            elif detail.amount == amount:
                                returned_price = amount * product.price

                                # Update product stock
                                cursor.execute(sql_queries.update_stock_product, (product.stock + amount, product.id))
                                connection.commit()

                                # Update invoice detail
                                cursor.execute(sql_queries.delete_sales_detail, (invoiceId, productId))
                                connection.commit()

                                # Delete or Update invoice
                                if returned_price == total_price:
                                    cursor.execute(sql_queries.delete_sales, (invoiceId))
                                    connection.commit()
                                else:
                                    cursor.execute(sql_queries.update_sales, (total_price - returned_price, invoiceId))
                                    connection.commit()

                                self.lineReturnedTotal.setText(str(round(total_price - returned_price,2)))
                                msg.setText(f"Returned Price is {returned_price}")
                                msg.exec_()
                            else:
                                msg.setIcon(QMessageBox.Warning)
                                msg.setText(f"More than purchased cannot be returned!!")
                                msg.exec_()
                else:
                    msg.setIcon(QMessageBox.Warning)
                    msg.setText(f"The product cannot be returned!!")
                    msg.exec_()
        self.lineProductId.clear()
        self.lineAmount.clear()




    def retranslateUi(self, ReturnedSalesDialog):
        _translate = QtCore.QCoreApplication.translate
        ReturnedSalesDialog.setWindowTitle(_translate("ReturnedSalesDialog", "Dialog"))
        self.lblId.setText(_translate("ReturnedSalesDialog", "Id:"))
        self.lblName.setText(_translate("ReturnedSalesDialog", "Name:"))
        self.lblRole.setText(_translate("ReturnedSalesDialog", "Role:"))
        self.label.setText(_translate("ReturnedSalesDialog", "<html><head/><body><p align=\"center\">Invoice</p></body></html>"))
        item = self.tableInvoice.horizontalHeaderItem(0)
        item.setText(_translate("ReturnedSalesDialog", "Product Id"))
        item = self.tableInvoice.horizontalHeaderItem(1)
        item.setText(_translate("ReturnedSalesDialog", "Photo"))
        item = self.tableInvoice.horizontalHeaderItem(2)
        item.setText(_translate("ReturnedSalesDialog", "Name"))
        item = self.tableInvoice.horizontalHeaderItem(3)
        item.setText(_translate("ReturnedSalesDialog", "Amount"))
        item = self.tableInvoice.horizontalHeaderItem(4)
        item.setText(_translate("ReturnedSalesDialog", "Price"))
        self.label_6.setText(_translate("ReturnedSalesDialog", "Invoice Id :"))
        self.btnShowInvoice.setText(_translate("ReturnedSalesDialog", "Show"))
        self.label_5.setText(_translate("ReturnedSalesDialog", "Returned Price :"))
        self.lineReturnedTotal.setText(_translate("ReturnedSalesDialog", "0.00"))
        self.label_2.setText(_translate("ReturnedSalesDialog", "Product Id :"))
        self.label_3.setText(_translate("ReturnedSalesDialog", "Amount :"))
        self.btnReturn.setText(_translate("ReturnedSalesDialog", "Return"))
